##standard user
ab_reservation_zenith_homepage:
    path:     /{_locale}/accueil-zenith
    defaults: { _controller: ABReservationZenithBundle:Default:index , _locale: fr }
    requirements:
        _locale: en|fr

gestion_langue:
    path:     /locale/{locale}/{vue}
    defaults: { _controller: ABReservationZenithBundle:Default:gestionLangue} 

gestion_theme:
    path:     /locale/{theme}/{vue}
    defaults: { _controller: ABReservationZenithBundle:Default:gestionTheme} 

about:
    path:   /Default/{_locale}/about
    defaults: { _controller: ABReservationZenithBundle:Default:about, _locale: fr }    
    requirements:
        _locale: en|fr 
 
##admin
backoffice_homepage:
    path:     /{_locale}/backoffice
    defaults: {_controller:ABReservationZenithBundle:Default:backoffice , _locale: fr }
    requirements:
        _locale: en|fr

##client
espaceclient_homepage:
    path:     /{_locale}/espaceclient
    defaults: { _controller: ABReservationZenithBundle:Default:espaceclient , _locale: fr }
    requirements:
     _locale: en|fr

## ajax_prix
ajax_prix:
    path:     /ajax/prix/{place}/{id_spectacle}
    defaults: { _controller: ABReservationZenithBundle:Ajax:getTarifWithPlace}     
    options:
        expose: true

ajax_seances:
    path:     /ajax/seances/{id_spectacle}
    defaults: { _controller: ABReservationZenithBundle:Ajax:getSeancesBySpectacle}     
    options:
        expose: true
##spectacle
index_spectacle:
    path:     /spectacle/{_locale}/index
    defaults: { _controller: ABReservationZenithBundle:Spectacle:index , _locale: fr }
    requirements:
        _locale: en|fr

ajouter_spectacle:
    path:     /spectacle/{_locale}/ajouter
    defaults: { _controller: ABReservationZenithBundle:Spectacle:ajouter , _locale: fr }
    requirements:
        _locale: en|fr

voir_spectacle:
    path:     /spectacle/{_locale}/voir/{id}
    defaults: { _controller: ABReservationZenithBundle:Spectacle:voir,id:0 , _locale: fr }
    requirements:
        _locale: en|fr

modifier_spectacle:
    path:     /spectacle/{_locale}/modifier/{id}
    defaults: { _controller: ABReservationZenithBundle:Spectacle:modifier , _locale: fr }
    requirements:
        _locale: en|fr

supprimer_spectacle:
    path: /reservation/supprimer/{id}
    defaults: { _controller: ABReservationZenithBundle:Spectacle:supprimer}
    


##seance
index_seance:
    path:     /seance/index
    defaults: { _controller: ABReservationZenithBundle:Seance:index }
    path:     /seance/{_locale}/index
    defaults: { _controller: ABReservationZenithBundle:Seance:index , _locale: fr }
    requirements:
        _locale: en|fr



modifier_seance:
    path:     /seance/{_locale}/modifier/{id}
    defaults: { _controller: ABReservationZenithBundle:Seance:modifier , _locale: fr }
    requirements:
        _locale: en|fr

voir_seance:
    path:     /seance/{_locale}/voir/{id_spectacle}/{id}
    defaults: { _controller: ABReservationZenithBundle:Seance:voir, id:0, id_spectacle:0 , _locale: fr }
    requirements:
        _locale: en|fr

supprimer_seance:
    path: /seance/supprimer/{id}
    defaults: { _controller: ABReservationZenithBundle:Seance:supprimer}



#tarif
index_tarif:
    path:     /tarif/{_locale}/index
    defaults: { _controller: ABReservationZenithBundle:Tarif:index , _locale: fr }
    requirements:
        _locale: en|fr



voir_tarif:
    path:     /tarif/{_locale}/voir/{id_spectacle}/{id}
    defaults: { _controller: ABReservationZenithBundle:Tarif:voir,id:0, id_spectacle:0 , _locale: fr }
    requirements:
        _locale: en|fr

modifier_tarif:
    path:     /tarif/{_locale}/modifier/{id}
    defaults: { _controller: ABReservationZenithBundle:Tarif:modifier , _locale: fr }
    requirements:
        _locale: en|fr

supprimer_tarif:
    path: /tarif/supprimer/{id}
    defaults: { _controller: ABReservationZenithBundle:Tarif:supprimer}


##reservation
index_reservation:
    path:     /reservation/{_locale}/index
    defaults: { _controller: ABReservationZenithBundle:Reservation:index  , _locale: fr }
    requirements:
        _locale: en|fr

ajouter_reservation:
    path:     /reservation/{_locale}/ajouter
    defaults: { _controller: ABReservationZenithBundle:Reservation:ajouter  , _locale: fr }
    requirements:
        _locale: en|fr

voir_reservation:
    path:     /reservation/{_locale}/voir/{idClient}/{id}
    defaults: { _controller: ABReservationZenithBundle:Reservation:voir,id:0, idClient:0 , _locale: fr }
    requirements:
        _locale: en|fr

modifier_reservation:
    path:     /reservation/{_locale}/modifier/{id}
    defaults: { _controller: ABReservationZenithBundle:Reservation:modifier , _locale: fr }
    requirements:
        _locale: en|fr

supprimer_reservation:
    path: /reservation/supprimer/{id}
    defaults: { _controller: ABReservationZenithBundle:Reservation:supprimer}

