services:
#    ab_reservation_zenith.example:
#        class: AB\ReservationZenithBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ab_reservation_zenith.locale_listener:
        class: AB\ReservationZenithBundle\Listener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
