<?php

namespace AB\ReservationZenithBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
	public function isLibre ($seance){
        $ok = true;
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('sp.id, sp.duree, se.heure')
           ->from('ABReservationZenithBundle:Spectacle','sp')
           ->leftJoin('ABReservationZenithBundle:Seance','se','WITH','se.spectacle=sp.id')
           ->where('se.date = ?1')
           ->setParameter(1,$seance->getDate());
        $query = $qb->getQuery();
        try {
            $result = $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return false;
        }        
        if($result){
                foreach ($result as $r) {
                    if($seance->getHeure()>=$r['heure'] && $seance->getHeure() <= ($r['heure']+strtotime('+'.$r['duree'].'minute'))){
                        if($ok){
                            $ok = false;
                        }
                    }
                }
        }
        return $ok;
        
    }

    public function updateNbPlace($seance, $action){
        $ok = true;
        $nbPlace = $seance->getNombrePlacesRestantes();
        if($action == 'add'){
            if(($nbPlace-1)>=0){
                $seance->setNombrePlacesRestantes($nbPlace-1);
                $em = $this->getEntityManager();
                $em->persist($seance);
                $em->flush();
            }else{
                $ok = false;
            }
        }else if($action == 'suppr'){
            if(($nbPlace+1)<=$seance->getSpectacle()->getNombrePlaces()){
                $seance->setNombrePlacesRestantes($nbPlace+1);
                $em = $this->getEntityManager();
                $em->persist($seance);
                $em->flush();
            }else{
                $ok = false;
            }
        }
        return $ok;
    }
	
}
