<?php

namespace AB\ReservationZenithBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends EntityRepository
{
	public function getTarifByPlace($place, $id_spectacle){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('t.id')
           ->from('ABReservationZenithBundle:Tarif','t')
           ->leftJoin('ABReservationZenithBundle:Spectacle','sp','WITH','t.spectacle=sp.id')
           ->where('t.spectacle= ?1 AND t.numeroPlaceMin <= ?2 AND t.numeroPlaceMax >= ?2')
           ->setParameter(1,$id_spectacle)
           ->setParameter(2,$place);
        $query = $qb->getQuery();
        $result = $query->getSingleResult();
        if($result){
          $tarif = $this->find($result['id']);
        }
        try {
            return $tarif;
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
