<?php

namespace AB\ReservationZenithBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends EntityRepository
{
	public function getTarifByPlace($place, $id_spectacle){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('t.prix')
           ->from('ABReservationZenithBundle:Tarif','t')
           ->leftJoin('ABReservationZenithBundle:Spectacle','sp','WITH','t.spectacle=sp.id')
           ->where('sp.id <= ?1 AND t.numeroPlaceMin <= ?2 AND t.numeroPlaceMax >= ?3')
           ->setParameter(1,$id_spectacle)
           ->setParameter(2,$place)
           ->setParameter(3,$place);
        $query = $qb->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
